import subprocess
from src.core.config import MODEL_NAME


def generate_code(prompt: str) -> str:
    try:
        full_prompt = f"""
You are an expert code modernization assistant.

Your task is to analyze legacy code and provide a structured response.

Follow this STRICT format:

1. Purpose:
Explain what the code does in 2-3 lines.

2. Key Components:
List important modules, functions, or logic.

3. Improvements:
Suggest improvements or modernization ideas.

IMPORTANT RULES:
- Do NOT hallucinate missing functionality
- Only use the provided code
- Be concise and clear
- Avoid unnecessary explanation

CODE:
{prompt}
"""

        result = subprocess.run(
            ["ollama", "run", MODEL_NAME],
            input=full_prompt.encode("utf-8"),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )

        output = result.stdout.decode("utf-8").strip()

        # Fallback if model gives empty output
        if not output:
            return "No response generated by model."

        return output

    except Exception as e:
        return f"Error while generating response: {str(e)}"